### DISCUSSION TITLE
Comparing dependencies-file plugin and Gradle's dependency locking

### DISCUSSION THREAD

**Discussion by simondean** [kronicle-tech/dependencies-file-gradle-plugin#24] [General]
Here's a short comparison between this plugin and [Gradle's dependency locking feature](https://docs.gradle.org/current/userguide/dependency_locking.html#lock_state_location_and_format)

# Side-by-side comparison

| Item | Gradle dependency locking | dependencies-file plugin |
|---|---|---|
| Purpose | Locking dependency versions when using dynamic dependency versions like `1.+` or `[1.0,2.0)` | Committing versions for all dependencies to Git, to aid with fixing dependency issues and for automated tooling to detect dependencies used |
| Simple to enable | :white_check_mark: | :white_check_mark: |
| Easy to update dependency files | :x: | :white_check_mark: |
| Build fails if dependencies do not match dependency files | :white_check_mark: | :x: |
| Dependency files are only written if build is successful | :white_check_mark: | :x: |
| Dependency files show relationships between dependencies | :x: | :white_check_mark: |
| Dependency file format | Property file format | YAML |

# Gradle dependency locking

## Enabling the feature

Enabling the feature for every project in a multi-project build: 

*build.gradle*
``` groovy
allprojects {
    dependencyLocking {
        lockAllConfigurations()
    }
}
```

## Updating dependency files

``` bash
./gradlew dependencies --write-locks
cd subproject1
../gradlew dependencies --write-locks
cd ../subproject2
../gradlew dependencies --write-locks
```

**gradle.lockfile**
```
# This is a Gradle generated file for dependency locking.
# Manual edits can break the build and are not advised.
# This file is expected to be part of source control.
org.springframework:spring-beans:5.0.5.RELEASE=compileClasspath, runtimeClasspath
org.springframework:spring-core:5.0.5.RELEASE=compileClasspath, runtimeClasspath
org.springframework:spring-jcl:5.0.5.RELEASE=compileClasspath, runtimeClasspath
empty=annotationProcessor
```

# dependencies-file plugin

## Enabling the feature

Enabling the feature for every project in a multi-project build: 

*build.gradle*
``` groovy
plugins {
    id "tech.kronicle.dependencies-file" version "0.1.16"
}

subprojects {
    apply plugin: "tech.kronicle.dependencies-file"
}
```

## Updating dependency files

Run any task that depends on the "assemble" task.  E.g. any of the following tasks.  Normally, performing a build or running tests, would be enough to update the dependency files.  

``` shell
./gradlew assemble
# or
./gradlew build
```

Alternatively, the `generateDependenciesFile` task can be executed directly: 

``` shell
./gradlew generateDependenciesFile
```

## Example Dependency File

**gradle-dependencies.yaml**
``` 
---
configurations:
- name: "runtimeClasspath"
  description: "Runtime classpath of source set 'main'."
  visible: false
  canBeResolved: true
  resolved: true
  resolvedDependencies:
  - name: "com.fasterxml.jackson.core:jackson-databind:2.13.3"
    direct: true
    dependencies:
    - name: "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
  - name: "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.3"
    direct: true
    dependencies:
    - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    - name: "com.fasterxml.jackson.core:jackson-databind:2.13.3"
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
    - name: "org.yaml:snakeyaml:1.30"
  - name: "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    dependencies:
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
  - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    dependencies:
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
  - name: "com.fasterxml.jackson.core:jackson-databind:2.13.3"
    dependencies:
    - name: "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
```
