### ISSUE TITLE
Dedup when same dependency is both a direct dependency and a transitive depenency 

### ISSUE THREAD

**Issue by simondean** [kronicle-tech/dependencies-file-gradle-plugin#28]
Example dependencies to dedup: 

``` yaml
  - name: "com.fasterxml.jackson.core:jackson-databind:2.13.3"
    direct: true
    dependencies:
    - name: "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
  - name: "com.fasterxml.jackson.core:jackson-databind:2.13.3"
    dependencies:
    - name: "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
```

The example should be dedupped to (the transitive copy is removed): 

``` yaml
  - name: "com.fasterxml.jackson.core:jackson-databind:2.13.3"
    direct: true
    dependencies:
    - name: "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
    - name: "com.fasterxml.jackson.core:jackson-core:2.13.3"
    - name: "com.fasterxml.jackson:jackson-bom:2.13.3"
```
